language: python
sudo: required

dist: bionic
group: edge

cache:
    pip: true

python:
    - 3.6
    - "3.6-dev"
    - "3.7-dev"

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install gcc python-socks libssl-dev swig p7zip-full unrar ssdeep libfuzzy-dev tor clamav-daemon -qq
    - sudo freshclam
    - sudo /etc/init.d/clamav-daemon start

install:
    - pip install -U -r requirements.txt
    - pip install -U tox-travis

script:
    - echo "exit" | python viper-cli
    - tox
    - tox -e pep8
