language: python
sudo: required

cache:
    pip: true

python:
    - 2.7
    - 3.5
    - "3.5-dev"
    - 3.6
    - "3.6-dev"

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install gcc python-socksipy libssl-dev swig p7zip-full unrar ssdeep libfuzzy-dev tor clamav-daemon -qq
    - sudo freshclam
    - sudo /etc/init.d/clamav-daemon start
install:
    - pip install -U -r requirements.txt
    - pip install -U tox-travis
script:
    - echo "exit" | python viper-cli
    - tox
    - tox -e pep8
